spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/aula_47
        username: postgres
        password: gui
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update

